name: Release

on:
  push:
    branches:
      - beta
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
      - 'feat/*'

env:
  DENO_DIR: .cache

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish package
        run: deno publish --dry-run
