name: Release

on:
  push:
    branches:
      - beta
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
      - 'feat/*'

permissions:
  contents: write

env:
  DENO_DIR: .cache

jobs:
  get-next-version:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install sematic-release plugins
        run: npm i semantic-release-export-data

      - run: npx semantic-release --dry-run
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      next-version: ${{ steps.get-next-version.outputs.new-release-version }}

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: get-next-version

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      - name: Show the next version
        run: echo "The new release version is ${{ needs.get-next-version.outputs.next-version }}"

      - name: Build binaries
        run: |
          echo ${{ needs.get-next-version.outputs.next-version }} | deno task add:version
          deno task build:linux
          deno task build:win
          deno task build:darwin-x64
          deno task build:darwin-arm64

      - name: Prepare distribution
        run: |
          cd dist
          for file in *; do tar -cvzf $file.tar.gz $file; done
          find . -type f -not -name '*.tar.gz' | xargs rm

      - name: Compute checksums
        run: |
          cd dist
          for file in *; do sha256sum $file >> checksums.txt; done

      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: trex
          path: dist/
          retention-days: 7

  # Release binaries to GitHub release
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: trex
          path: dist/

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Publish TS to JSR
  # publish:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   needs: release

  #   permissions:
  #     contents: read
  #     id-token: write

  #   steps:
  #     - name: Setup repo
  #       uses: actions/checkout@v4

  #     - name: Setup Deno
  #       uses: denoland/setup-deno@v1
  #       with:
  #         deno-version: v1.x

  #     - name: Publish package
  #       run: deno publish
