name: Release

on:
  push:
    branches:
      - beta
      - main
      - '[0-9]+.x'
      - '[0-9]+.[0-9]+.x'
      - 'feat/*'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Copy package.json and package-lock.json
        run: |
          cp ./.github/workflows/release/package.json .
          cp ./.github/workflows/release/package-lock.json .

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: npm

      - name: Install release dependencies
        run: npm ci

      - name: Run semantic-release
        run: npx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
