name: Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Lets see what we have
        run: ls -la

      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 21.x
      #     cache: npm

      # - name: Install release dependencies
      #   run: npm ci

      # - name: Release
      #   uses: codfish/semantic-release-action@v3
      #   with:
      #     dry-run: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
